version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./database:/app/database
      - ./backend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - chroma

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_API_URL=http://localhost:3001

  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - ./database/chroma:/chroma/chroma

  whatsapp-bridge:
    build: ./tools/whatsapp-bridge
    ports:
      - "8080:8080"
    volumes:
      - ./database/store:/app/store